
services:
  #API Server
  api_server:
    build: ./api_server
    container_name: api_server
    ports:
      - "8000:8000"
    volumes:
      - ./api_server:/app
    networks:
      - dragonfly_net

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "9000:8501"
    volumes:
      - ./dashboard:/app
    networks:
      - dragonfly_net
    depends_on:
      - api_server

networks:
  dragonfly_net:
    driver: bridge